site_name = "ST·U News"
author_name = "STU News"
about = """
some news about ShanTou University.

<p style="color:red">NOTE：UNOFFICIAL!</p>

本站支持 RSS 订阅：[https://news.shantou.university/feed.xml](https://news.shantou.university/feed.xml)

Maintained by: dev@ShanTou.University


AD: [在问AI：有疑问，找在问！](https://www.zaiwenai.com/?channel-code=684599a7376e70be2019f6d4)
"""
blogroll_feeds = ""
